-- Admin login (Better Auth): the owner's account, sessions (one row per device), password hash,
-- sign-in codes, two-factor state and rate-limit counters. Generated by scripts/auth-schema.mjs from
-- src/server/auth-options.mjs (Better Auth 1.7.7); made idempotent by hand.

CREATE TABLE IF NOT EXISTS "admin_users" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null, "twoFactorEnabled" boolean);

CREATE TABLE IF NOT EXISTS "admin_sessions" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "admin_users" ("id") on delete cascade);

CREATE TABLE IF NOT EXISTS "admin_accounts" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "admin_users" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

CREATE TABLE IF NOT EXISTS "admin_verifications" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

CREATE TABLE IF NOT EXISTS "admin_two_factor" ("id" text not null primary key, "secret" text not null, "backupCodes" text not null, "userId" text not null references "admin_users" ("id") on delete cascade, "verified" boolean, "failedVerificationCount" integer, "lockedUntil" timestamptz);

CREATE TABLE IF NOT EXISTS "admin_rate_limits" ("id" text not null primary key, "key" text not null unique, "count" integer not null, "lastRequest" bigint not null);

CREATE INDEX IF NOT EXISTS "admin_sessions_userId_idx" on "admin_sessions" ("userId");

CREATE INDEX IF NOT EXISTS "admin_accounts_userId_idx" on "admin_accounts" ("userId");

CREATE INDEX IF NOT EXISTS "admin_verifications_identifier_idx" on "admin_verifications" ("identifier");

CREATE INDEX IF NOT EXISTS "admin_two_factor_secret_idx" on "admin_two_factor" ("secret");

CREATE INDEX IF NOT EXISTS "admin_two_factor_userId_idx" on "admin_two_factor" ("userId");
