import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Instrument_Serif, Noto_Sans_Bengali } from "next/font/google";
import { PreviewBar } from "@/components/admin/preview-bar";
import { ThemeProvider } from "@/components/theme-provider";
import { JsonLd } from "@/components/site/site-shell";
import { PersonaProvider } from "@/lib/persona/context";
import { lt } from "@/lib/persona/text";
import { graph, personLd, websiteLd } from "@/lib/seo";
import { siteUrl } from "@/lib/site";
import { clientView } from "@/server/persona/compile";
import { headers } from "next/headers";
import type { PersonaDoc } from "@/lib/persona/schema";
import { currentPersona } from "@/server/persona/resolve";
import { personaOrigin } from "@/server/persona/urls";

/** The job persona keeps NEXT_PUBLIC_SITE_URL (as before); others use their own address (see urls.ts). */
const legacyOrigin = (doc: PersonaDoc) => (doc.legacy ? (doc.site.url ?? siteUrl) : undefined);
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
// Mono and the serif only style small labels and quotes: not preloaded, so they never compete with the hero text.
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"], preload: false });
const serif = Instrument_Serif({ variable: "--font-instrument", subsets: ["latin"], weight: "400", style: ["normal", "italic"], preload: false });
// Self-hosted like the others (the CSP allows fonts from this site only). Only fetched for Bangla text.
const bengali = Noto_Sans_Bengali({ variable: "--font-bengali", subsets: ["bengali"], preload: false });

/**
 * Every page is rendered per request: which persona it shows depends on the host (or path prefix),
 * the persona's content is whatever was last published (no rebuild), and visitors with an access code
 * see more. The persona's texts come from src/server/persona.
 */
export async function generateMetadata(): Promise<Metadata> {
  const persona = await currentPersona();
  const { compiled, lang } = persona;
  const { doc } = compiled;
  const id = doc.identity;
  const role = lt(id.role, lang);
  const name = role ? `${id.name} - ${role}` : id.name;
  const description = lt(doc.site.description, lang) || lt(id.headline, lang) || name;
  const origin = legacyOrigin(doc) ?? personaOrigin(persona, await headers());
  const legacy = doc.legacy;
  return {
    metadataBase: new URL(origin),
    title: { default: lt(doc.site.title, lang) || name, template: `%s - ${id.name}` },
    description,
    openGraph: {
      type: "website",
      siteName: id.name,
      url: origin,
      title: lt(doc.site.title, lang) || name,
      description: legacy ? "A portfolio you can chat with. Lead full-stack engineer - React, Next.js, NestJS, AWS." : description,
      // Generated by src/app/og.png/route.tsx (the job persona's card); a path with an extension skips the trailingSlash redirect.
      images: legacy ? [{ url: "/og.png", width: 1200, height: 630, alt: name }] : undefined,
      locale: lang === "bn" ? "bn_BD" : "en_US",
    },
    twitter: legacy ? { card: "summary_large_image", images: ["/og.png"] } : { card: "summary" },
    applicationName: id.name,
    authors: [{ name: id.name, url: origin }],
    creator: id.name,
    publisher: id.name,
    category: legacy ? "technology" : undefined,
    formatDetection: { telephone: false },
    ...(doc.site.indexable && !persona.preview ? {} : { robots: { index: false, follow: false } }),
    // Search Console / Bing Webmaster verification: set the tokens in the server env (never secret, but per site).
    verification: {
      google: process.env.GOOGLE_SITE_VERIFICATION || undefined,
      other: process.env.BING_SITE_VERIFICATION ? { "msvalidate.01": process.env.BING_SITE_VERIFICATION } : undefined,
    },
  };
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f6f4ef" },
    { media: "(prefers-color-scheme: dark)", color: "#1a1a1c" },
  ],
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const persona = await currentPersona();
  const view = clientView(persona.compiled, persona.tier, persona.lang);
  return (
    <html
      lang={persona.lang}
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${serif.variable} ${bengali.variable} antialiased`}
    >
      <body>
        {/* One Person + WebSite graph on every indexable page; pages add their own nodes that reference these @ids. */}
        {persona.compiled.doc.site.indexable && persona.compiled.doc.legacy && <JsonLd data={graph(personLd(), websiteLd())} />}
        <ThemeProvider>
          <PersonaProvider value={view} base={persona.base}>
            {children}
          </PersonaProvider>
          {persona.preview && <PreviewBar name={persona.compiled.doc.name} tier={persona.tier} invalid={!!persona.preview.invalid} />}
        </ThemeProvider>
      </body>
    </html>
  );
}
