import { createElement } from "react";
import {
  Award,
  Baby,
  Book,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  CircleHelp,
  Clock,
  Cloud,
  Code2,
  Coffee,
  Download,
  Dumbbell,
  FileText,
  FlaskConical,
  Globe,
  GraduationCap,
  Hammer,
  HandHeart,
  Heart,
  HeartHandshake,
  House,
  Image,
  KeyRound,
  Languages,
  Leaf,
  Lightbulb,
  ListChecks,
  Lock,
  type LucideIcon,
  Mail,
  MapPin,
  MessageSquareHeart,
  MessageSquareText,
  Moon,
  Music,
  Phone,
  Plane,
  Quote,
  Rocket,
  Ruler,
  ShieldCheck,
  Shuffle,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Sun,
  User,
  UserRound,
  Users,
  Utensils,
  Wallet,
  Zap,
} from "lucide-react";

/**
 * Icons a persona's questions may use, by name. Personas live in the database as JSON, so they store a
 * name and the UI looks the component up here (unknown names fall back to "sparkles").
 */
export const ICONS = {
  award: Award,
  baby: Baby,
  book: Book,
  "book-open": BookOpen,
  briefcase: Briefcase,
  building: Building2,
  calendar: Calendar,
  camera: Camera,
  help: CircleHelp,
  clock: Clock,
  cloud: Cloud,
  code: Code2,
  coffee: Coffee,
  download: Download,
  dumbbell: Dumbbell,
  "file-text": FileText,
  flask: FlaskConical,
  globe: Globe,
  "graduation-cap": GraduationCap,
  hammer: Hammer,
  "hand-heart": HandHeart,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  house: House,
  image: Image,
  key: KeyRound,
  languages: Languages,
  leaf: Leaf,
  lightbulb: Lightbulb,
  "list-checks": ListChecks,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  "message-heart": MessageSquareHeart,
  message: MessageSquareText,
  moon: Moon,
  music: Music,
  phone: Phone,
  plane: Plane,
  quote: Quote,
  rocket: Rocket,
  ruler: Ruler,
  "shield-check": ShieldCheck,
  shuffle: Shuffle,
  smile: Smile,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  sun: Sun,
  user: User,
  "user-round": UserRound,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
export const ICON_NAMES = Object.keys(ICONS) as IconName[];

export const iconFor = (name: string | undefined): LucideIcon => (name && name in ICONS ? ICONS[name as IconName] : Sparkles);

/** The name of a lucide component, if it is one of ours (used when importing the code content). */
export const iconName = (icon: LucideIcon): IconName | undefined => ICON_NAMES.find((n) => ICONS[n] === icon);

/** A question's icon by name. (The component is looked up, not created, so it keeps its identity.) */
export function QIcon({ name, className }: { name: string | undefined; className?: string }) {
  return createElement(iconFor(name), { className, "aria-hidden": true });
}
