import type { Lang } from "./types";

/**
 * Words the chat shell shows, per language. A persona overrides any of them (the job persona keeps
 * "CV" and "Reading my CV..."; the marriage persona says "Biodata"). {name} and {shortName} are filled
 * in from the persona's identity. `**bold**` works wherever the text is rendered with RichText.
 * In "availability", [square brackets] mark words only shown on wider screens: "Open to [new ]roles".
 */
export const LABEL_KEYS = [
  "askAbout",
  "newChat",
  "composerPlaceholder",
  "composerPlaceholderAi",
  "composerAria",
  "composerNoMatch",
  "askHint",
  "askHintNoMatch",
  "thinking",
  "thinkingStatus",
  "aiDisclaimer",
  "footerAi",
  "footerNoAi",
  "pickHintBefore",
  "pickHintAfter",
  "aiStopped",
  "aiLabel",
  "documentButton",
  "documentDownload",
  "documentWeb",
  "availability",
  "availabilityTitle",
  "notFoundTitle",
  "notFoundText",
  "notFoundBack",
  "gatedText",
  "requestAccess",
  "enterCode",
  "unlockedBadge",
  "languageSwitch",
  "unlockButton",
  "codeWrong",
  "codeLimited",
  "codeUnlocked",
  "lockAgain",
  "requestTitle",
  "requestName",
  "requestRelation",
  "requestPhone",
  "requestEmail",
  "requestMessage",
  "requestSend",
  "requestSent",
  "requestNeedContact",
  "documentLocked",
  "printButton",
] as const;

export type LabelKey = (typeof LABEL_KEYS)[number];
export type Labels = Record<LabelKey, string>;

export const isLabelKey = (k: string): k is LabelKey => (LABEL_KEYS as readonly string[]).includes(k);

const en: Labels = {
  askAbout: "Ask about",
  newChat: "New chat",
  composerPlaceholder: "Ask me a question…",
  composerPlaceholderAi: "Ask me anything…",
  composerAria: "Ask a question about {shortName}",
  composerNoMatch: "I only answer questions about {shortName}. Press **Enter** anyway, or pick a listed question.",
  askHint: "The AI answers from what I've shared",
  askHintNoMatch: "No ready-made answer for that - the AI answers from what I've shared",
  thinking: "Thinking...",
  thinkingStatus: "Thinking",
  aiDisclaimer: "Answered by AI from what I've shared - it can be imperfect.",
  footerAi: "Listed answers are written by me; anything else is answered by AI, from my own notes only.",
  footerNoAi: "Every answer here is written by me - nothing is generated.",
  pickHintBefore: "Pick a question or type",
  pickHintAfter: "to see everything you can ask.",
  aiStopped: "Stopped. Ask me anything else whenever you like.",
  aiLabel: "AI answer",
  documentButton: "Download",
  documentDownload: "Download",
  documentWeb: "Web version",
  availability: "Say hello",
  availabilityTitle: "Get in touch",
  notFoundTitle: "I don't know that one.",
  notFoundText: "This page doesn't exist - but the chat can answer your questions.",
  notFoundBack: "Back to the chat",
  gatedText: "That part is shared privately. If you have an access code, enter it below - or request access and I'll get back to you.",
  requestAccess: "Request access",
  enterCode: "Enter your access code",
  unlockedBadge: "Private details unlocked",
  languageSwitch: "বাংলা",
  unlockButton: "Unlock",
  codeWrong: "That code didn't work. Check it and try again.",
  codeLimited: "Too many tries. Please wait a few minutes.",
  codeUnlocked: "Unlocked: you can now see the private details too.",
  lockAgain: "Hide the private details again",
  requestTitle: "Ask for access",
  requestName: "Your name",
  requestRelation: "How you are connected (for example: guardian)",
  requestPhone: "Phone",
  requestEmail: "Email (optional)",
  requestMessage: "Message",
  requestSend: "Send request",
  requestSent: "Request sent. You'll get a reply soon.",
  requestNeedContact: "Add a phone number or an email address.",
  documentLocked: "This document is shared with people who have an access code.",
  printButton: "Print",
};

const bn: Labels = {
  askAbout: "জিজ্ঞেস করুন",
  newChat: "নতুন চ্যাট",
  composerPlaceholder: "একটি প্রশ্ন লিখুন…",
  composerPlaceholderAi: "আমাকে যেকোনো কিছু জিজ্ঞেস করুন…",
  composerAria: "{shortName} সম্পর্কে প্রশ্ন করুন",
  composerNoMatch: "আমি শুধু {shortName} সম্পর্কে প্রশ্নের উত্তর দিই। তবুও **Enter** চাপুন, অথবা তালিকা থেকে একটি প্রশ্ন বেছে নিন।",
  askHint: "আমার দেওয়া তথ্য থেকে AI উত্তর দেয়",
  askHintNoMatch: "এর জন্য লেখা উত্তর নেই - আমার দেওয়া তথ্য থেকে AI উত্তর দেয়",
  thinking: "ভাবছি...",
  thinkingStatus: "ভাবছি",
  aiDisclaimer: "আমার দেওয়া তথ্য থেকে AI এই উত্তর লিখেছে - ভুল থাকতে পারে।",
  footerAi: "তালিকার উত্তরগুলো আমার নিজের লেখা; বাকি প্রশ্নের উত্তর AI দেয়, শুধু আমার দেওয়া তথ্য থেকে।",
  footerNoAi: "এখানকার প্রতিটি উত্তর আমার নিজের লেখা।",
  pickHintBefore: "একটি প্রশ্ন বেছে নিন অথবা লিখুন",
  pickHintAfter: "- সব প্রশ্ন দেখতে।",
  aiStopped: "থামানো হয়েছে। যখন খুশি অন্য কিছু জিজ্ঞেস করুন।",
  aiLabel: "AI উত্তর",
  documentButton: "ডাউনলোড",
  documentDownload: "ডাউনলোড",
  documentWeb: "ওয়েব সংস্করণ",
  availability: "যোগাযোগ [করুন]",
  availabilityTitle: "যোগাযোগ করুন",
  notFoundTitle: "এই পাতাটি নেই।",
  notFoundText: "পাতাটি খুঁজে পাওয়া যায়নি - তবে চ্যাটে আপনার প্রশ্নের উত্তর পাবেন।",
  notFoundBack: "চ্যাটে ফিরে যান",
  gatedText: "এই অংশটি ব্যক্তিগতভাবে শেয়ার করা হয়। আপনার কাছে অ্যাক্সেস কোড থাকলে নিচে লিখুন - অথবা অনুরোধ পাঠান, আমি যোগাযোগ করব।",
  requestAccess: "অনুরোধ পাঠান",
  enterCode: "অ্যাক্সেস কোড লিখুন",
  unlockedBadge: "ব্যক্তিগত তথ্য খোলা হয়েছে",
  languageSwitch: "English",
  unlockButton: "খুলুন",
  codeWrong: "কোডটি কাজ করেনি। দেখে আবার চেষ্টা করুন।",
  codeLimited: "অনেকবার চেষ্টা হয়েছে। কয়েক মিনিট পরে আবার চেষ্টা করুন।",
  codeUnlocked: "খোলা হয়েছে: এখন ব্যক্তিগত তথ্যও দেখতে পাবেন।",
  lockAgain: "ব্যক্তিগত তথ্য আবার লুকান",
  requestTitle: "অ্যাক্সেসের অনুরোধ",
  requestName: "আপনার নাম",
  requestRelation: "আপনার সম্পর্ক (যেমন: অভিভাবক)",
  requestPhone: "ফোন",
  requestEmail: "ইমেইল (ঐচ্ছিক)",
  requestMessage: "বার্তা",
  requestSend: "অনুরোধ পাঠান",
  requestSent: "অনুরোধ পাঠানো হয়েছে। শিগগিরই উত্তর পাবেন।",
  requestNeedContact: "একটি ফোন নম্বর বা ইমেইল দিন।",
  documentLocked: "এই নথি শুধু অ্যাক্সেস কোড থাকা ব্যক্তিদের সাথে শেয়ার করা হয়।",
  printButton: "প্রিন্ট",
};

export const LABEL_DEFAULTS: Record<Lang, Labels> = { en, bn };
